<<<<<<< HEAD
=======
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v6.30.1
// source: google/protobuf/struct.proto

>>>>>>> 571bc0a70ddfee10708e0b3f6c983db39b1abd2d
/* eslint-disable */
import { wrappers } from "protobufjs";

export const protobufPackage = "google.protobuf";

/**
 * `NullValue` is a singleton enumeration to represent the null value for the
 * `Value` type union.
 *
 * The JSON representation for `NullValue` is JSON `null`.
 */
export enum NullValue {
  /** NULL_VALUE - Null value. */
  NULL_VALUE = 0,
  UNRECOGNIZED = -1,
}

/**
 * `Struct` represents a structured data value, consisting of fields
 * which map to dynamically typed values. In some languages, `Struct`
 * might be supported by a native representation. For example, in
 * scripting languages like JS a struct is represented as an
 * object. The details of that representation are described together
 * with the proto support for the language.
 *
 * The JSON representation for `Struct` is JSON object.
 */
export interface Struct {
  /** Unordered map of dynamically typed values. */
  fields: { [key: string]: any | undefined };
}

export interface Struct_FieldsEntry {
  key: string;
  value: any | undefined;
}

/**
 * `Value` represents a dynamically typed value which can be either
 * null, a number, a string, a boolean, a recursive struct value, or a
 * list of values. A producer of value is expected to set one of these
 * variants. Absence of any variant indicates an error.
 *
 * The JSON representation for `Value` is JSON value.
 */
export interface Value {
  /** Represents a null value. */
  nullValue?:
    | NullValue
    | undefined;
  /** Represents a double value. */
  numberValue?:
    | number
    | undefined;
  /** Represents a string value. */
  stringValue?:
    | string
    | undefined;
  /** Represents a boolean value. */
  boolValue?:
    | boolean
    | undefined;
  /** Represents a structured value. */
  structValue?:
    | { [key: string]: any }
    | undefined;
  /** Represents a repeated `Value`. */
  listValue?: Array<any> | undefined;
}

/**
 * `ListValue` is a wrapper around a repeated field of values.
 *
 * The JSON representation for `ListValue` is JSON array.
 */
export interface ListValue {
  /** Repeated field of dynamically typed values. */
  values: any[];
}

export const GOOGLE_PROTOBUF_PACKAGE_NAME = "google.protobuf";

function createBaseStruct(): Struct {
  return { fields: {} };
}

<<<<<<< HEAD
export const Struct = {
  wrap(object: { [key: string]: any } | undefined): Struct {
    const struct = createBaseStruct();
    if (object !== undefined) {
      Object.keys(object).forEach((key) => {
        struct.fields[key] = Value.wrap(object[key]);
      });
=======
export const Struct: MessageFns<Struct> & StructWrapperFns = {
  wrap(object: { [key: string]: any } | undefined): Struct {
    const struct = createBaseStruct();

    if (object !== undefined) {
      for (const key of Object.keys(object)) {
        struct.fields[key] = Value.wrap(object[key]);
      }
>>>>>>> 571bc0a70ddfee10708e0b3f6c983db39b1abd2d
    }
    return struct;
  },

  unwrap(message: Struct): { [key: string]: any } {
    const object: { [key: string]: any } = {};
    if (message.fields) {
<<<<<<< HEAD
      Object.keys(message.fields).forEach((key) => {
        object[key] = Value.unwrap(message.fields[key]);
      });
=======
      for (const key of Object.keys(message.fields)) {
        object[key] = Value.unwrap(message.fields[key]);
      }
>>>>>>> 571bc0a70ddfee10708e0b3f6c983db39b1abd2d
    }
    return object;
  },
};

function createBaseValue(): Value {
  return {};
}

<<<<<<< HEAD
export const Value = {
=======
export const Value: MessageFns<Value> & AnyValueWrapperFns = {
>>>>>>> 571bc0a70ddfee10708e0b3f6c983db39b1abd2d
  wrap(value: any): Value {
    const result = {} as any;
    if (value === null) {
      result.nullValue = NullValue.NULL_VALUE;
    } else if (typeof value === "boolean") {
      result.boolValue = value;
    } else if (typeof value === "number") {
      result.numberValue = value;
    } else if (typeof value === "string") {
      result.stringValue = value;
<<<<<<< HEAD
    } else if (Array.isArray(value)) {
=======
    } else if (globalThis.Array.isArray(value)) {
>>>>>>> 571bc0a70ddfee10708e0b3f6c983db39b1abd2d
      result.listValue = ListValue.wrap(value);
    } else if (typeof value === "object") {
      result.structValue = Struct.wrap(value);
    } else if (typeof value !== "undefined") {
<<<<<<< HEAD
      throw new Error("Unsupported any value type: " + typeof value);
=======
      throw new globalThis.Error("Unsupported any value type: " + typeof value);
>>>>>>> 571bc0a70ddfee10708e0b3f6c983db39b1abd2d
    }
    return result;
  },

  unwrap(message: any): string | number | boolean | Object | null | Array<any> | undefined {
    if (message?.hasOwnProperty("stringValue") && message.stringValue !== undefined) {
      return message.stringValue;
    } else if (message?.hasOwnProperty("numberValue") && message?.numberValue !== undefined) {
      return message.numberValue;
    } else if (message?.hasOwnProperty("boolValue") && message?.boolValue !== undefined) {
      return message.boolValue;
    } else if (message?.hasOwnProperty("structValue") && message?.structValue !== undefined) {
      return Struct.unwrap(message.structValue as any);
    } else if (message?.hasOwnProperty("listValue") && message?.listValue !== undefined) {
      return ListValue.unwrap(message.listValue);
    } else if (message?.hasOwnProperty("nullValue") && message?.nullValue !== undefined) {
      return null;
    }
    return undefined;
  },
};

function createBaseListValue(): ListValue {
  return { values: [] };
}

<<<<<<< HEAD
export const ListValue = {
=======
export const ListValue: MessageFns<ListValue> & ListValueWrapperFns = {
>>>>>>> 571bc0a70ddfee10708e0b3f6c983db39b1abd2d
  wrap(array: Array<any> | undefined): ListValue {
    const result = createBaseListValue();
    result.values = (array ?? []).map(Value.wrap);
    return result;
  },

  unwrap(message: ListValue): Array<any> {
<<<<<<< HEAD
    if (message?.hasOwnProperty("values") && Array.isArray(message.values)) {
=======
    if (message?.hasOwnProperty("values") && globalThis.Array.isArray(message.values)) {
>>>>>>> 571bc0a70ddfee10708e0b3f6c983db39b1abd2d
      return message.values.map(Value.unwrap);
    } else {
      return message as any;
    }
  },
};

wrappers[".google.protobuf.Struct"] = { fromObject: Struct.wrap, toObject: Struct.unwrap } as any;
<<<<<<< HEAD
=======

export interface MessageFns<T> {
}

export interface StructWrapperFns {
  wrap(object: { [key: string]: any } | undefined): Struct;
  unwrap(message: Struct): { [key: string]: any };
}

export interface AnyValueWrapperFns {
  wrap(value: any): Value;
  unwrap(message: any): string | number | boolean | Object | null | Array<any> | undefined;
}

export interface ListValueWrapperFns {
  wrap(array: Array<any> | undefined): ListValue;
  unwrap(message: ListValue): Array<any>;
}
>>>>>>> 571bc0a70ddfee10708e0b3f6c983db39b1abd2d
